import 'dart:io';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import '../../core/constants/app_string.dart';
import '/shared/utils/validator_extension.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import '../../core/constants/app_color.dart';
import 'text_widget.dart';

part 'solid_button.dart';
part 'loading_widget.dart';
part 'no_data_found_widget.dart';
part 'image_placeholder_widget.dart';
part 'text_field_widget.dart';
part 'list_refresh_ndicator.dart';
part 'card_widget.dart';
part 'app_scaffold.dart';
